@startuml ui_interface_class_diagram
'Understand the code from interface(REST) to UI'
/'
 // Calling API for all the api interaction
'/

/'Load have the api calling and build the feed list
Add item to context.bumper list
reset the feed context
target based URL
List of endpoint
1. /All
2. /all?unread=true
3. ../api/subscription/{id}
4. ../api/category/{id}
'/
package "Content Subsystem"{
  package "Webapp"{
    class feed {
      -String title
      -String url
      -List articles
      
      +void load()
      +void triggerPaging()
      +void cache()
      +void reset() 
      +void init()
    }

    'Build the feed list, add all meta data and display the feed list'
    class article {
      -String title 
      -String content
      -Date publishDate
      -boolean isRead
      
      +void build()
      +void read()
      +void top()
    }

    class util {
      +init(): void
      +ajax(): XMLHttpRequest
      +buildLoader(): String
      +escape(): String
    }

    feed --> article : contains
    feed --> util : uses
  }

  package "com.sismics.reader.rest.resource" {
    abstract class BaseResource {
        - HttpServletRequest request
        - String appKey
        - IPrincipal principal

        # boolean authenticate()
        # void checkBaseFunction()
        # boolean hasBaseFunction()
    }

    class AllResource {
        + Response get()
        + Response read()
    }

    class ArticleResource {
        + Response read()
        + Response readMultiple()
        + Response unread()
        + Response unreadMultiple()
    }
    
    class StarredResource {
        + Response get()
        + Response star()
        + Response unstar()
        + Response starMultiple()
        + Response unstarMultiple()
    }

    class CategoryResource {
        + Response list()
        + Response get()
        + Response add()
        + Response delete()
        + Response read()
        + Response update()
    }

    class SubscriptionResource {
        + Response list()
        + Response get()
        + Response getSynchronization()
        + Response add()
        + Response update()
        + Response favicon()
        + Response read()
        + Response delete()
        + Response importFile()
        + Response export()
    }

    AllResource --|> BaseResource
    ArticleResource --|> BaseResource
    StarredResource --|> BaseResource
    CategoryResource --|> BaseResource
    SubscriptionResource --|> BaseResource
  }

  package "com.sismics.util.jpa" {
    abstract class BaseDao {
        + void findByCriteria()
        + List findByCriteria()
        + T findFirstByCriteria()
        # QueryParam getQueryParam()
    }
  }

  package "com.sismics.reader.core.dao.jpa" {
    class CategoryDao {
        + Category getRootCategory()
        + Category getCategory()
        + int getCategoryCount()
        + String create()
        + void update()
        + void delete()
        + void reorder()
    }

    class UserArticleDao {
        + UserArticle getUserArticle()
        + void update()
        + void markAsRead()
    }

    class ArticleDao {
        + QueryParam getQueryParam()
        + String create()
        + Article update()
        + List findAll()
        + void delete()
    }

    class FeedDao {
        + QueryParam getQueryParam()
        + Feed getByRssUrl()
        + String create()
        + void delete()
        + Feed getByRssUrl()
        + Feed update()
    }

    class FeedSynchronizationDao {
        + void create()
        + void deleteOldFeedSynchronization()
        + List findByFeedId()
    }

    class FeedSubscriptionDao {
        + void update()
        + void reorder()
        + void delete()
        + String create()
        + void reorder()
        + void updateUnreadCount()
        + FeedSubscription getFeedSubscription()
    }
  }
  ArticleDao --|> BaseDao
  UserArticleDao --|> BaseDao
  FeedSubscriptionDao --|> BaseDao
  FeedDao --|> BaseDao

  AllResource --> UserArticleDao : Uses
  AllResource --> FeedSubscriptionDao : Uses
  ArticleResource --> UserArticleDao : Uses
  ArticleResource --> ArticleDao : Uses
  ArticleResource --> FeedSubscriptionDao : Uses
  StarredResource --> UserArticleDao : Uses
  CategoryResource --> CategoryDao : Uses
  CategoryResource --> FeedSubscriptionDao : Uses
  CategoryResource --> UserArticleDao : Uses
  SubscriptionResource --> FeedSubscriptionDao : Uses
  SubscriptionResource --> FeedDao : Uses
  SubscriptionResource --> UserArticleDao : Uses
  SubscriptionResource --> FeedSynchronizationDao : Uses
  SubscriptionResource --> CategoryDao : Uses
  SubscriptionResource --> UserDao : Uses
  SubscriptionResource --> FeedService : Uses

  package "com.sismics.reader.core.model.jpa" {
    class Article {
        - String id
        - String feedId
        - String url
        - String baseUri
        - String guid
        - String title
        - String creator
        - String description
        - String commentUrl
        - Integer commentCount
        - String enclosureUrl
        - Integer enclosureLength
        - String enclosureType
        - Date publicationDate
        - Date createDate
        - Date deleteDate
    }

    class UserArticle {
        - String id
        - String userId
        - String articleId
        - Date createDate
        - Date readDate
        - Date starredDate
        - Date deleteDate
    }

    class Category {
        - String id
        - String name
        - String userId
        - String parentId
        - int order
        - boolean folded
        - Date createDate
        - Date deleteDate
    }

    class FeedSubscription {
        - String id
        - String userId
        - String feedId
        - String categoryId
        - String title
        - Integer order
        - int unreadCount
        - Date createDate
        - Date deleteDate
    }

    class FeedSynchronization {
        - String feedId
        - boolean success
        - String message
        - int duration
    }

    class Feed {
        - String id
        - String rssUrl
        - String url
        - String baseUri
        - String title
        - String language
        - String description
        - Date createDate
        - Date lastFetchDate
        - Date deleteDate
    }
  }
  ArticleDao --> Article : Uses
  UserArticleDao --> UserArticle : Uses
  FeedSubscriptionDao --> FeedSubscription : Uses
  CategoryDao --> Category : Uses

  package "com.sismics.reader.core.service" {
    class FeedService {
        + void synchronizeAllFeeds()
        + Feed synchronize()
        + void createInitialUserArticle()
        - boolean isFaviconUpdated()
        - RssReader parseFeedOrPage()
        - void logParsingError()
        - void completeArticleList()
        - List getArticleToRemove()
        - List getNewerArticleList()
        - Article getOldestArticle()
    }
  }

  FeedService --> FeedDao : Uses
  FeedService --> ArticleDao : Uses
  FeedService --> UserArticleDao : Uses
  FeedService --> FeedSubscriptionDao : Uses
  FeedService --> FeedSynchronizationDao : Uses
  FeedService --> Feed : Uses
  FeedService --> Article : Uses
  FeedService --> UserArticle : Uses
  FeedService --> FeedSubscription : Uses
  FeedService --> FeedSynchronization : Uses
}

@enduml